### ISSUE TITLE
Dashboard-component - Clean up / optimization

### ISSUE THREAD

**Issue by Kajlax** [Kajlax/Rdp#14]
Is there some smart ways/optimization that can be done to the Dashboard-component?

- Can DashboardBarChart function be changed to a class component?
- Is the JSON-file hierarchy optimal/correct?

**Comment by LauriKatajisto** [comment]
https://github.com/Kajlax/Rdp/pull/15

**Comment by Kajlax** [comment]
Sweet! Now the code looks really good!
