### ISSUE TITLE
Gallery-component - Dimmer-functionality

### ISSUE THREAD

**Issue by Kajlax** [Kajlax/Rdp#9]
Dimmer-functionality not yet working. When a single image is clicked the page dims and the current image, id-text and category-text is shown. Full code in Gallery.js.

`<Dimmer active={active} onClickOutside={this.handleClose} page>
        <Image rounded src={this.imageUrl} />
        <Header as="h2" inverted>
          {this.id}, {this.imageCategory}
        </Header>
      </Dimmer>`

**Comment by LauriKatajisto** [comment]
https://github.com/Kajlax/Rdp/pull/11
